"""Briefing tab — full-document morning briefing generated by Claude."""
from __future__ import annotations
from datetime import date
from nicegui import ui, run
from models.schema import AppState
from components.macro_views import DIRECTION_COLORS, _conviction_bars_html
from components.asset_views import SCORE_COLORS, _load_tenure_data
from components.status_bar import days_since, staleness_color, staleness_label
from services.talking_points import MACRO_FRED_MAP, VERBAL_SCORE, fred_snippet, macro_prose
from services.llm_polish import (
    available as llm_available,
    generate_briefing,
    get_cached_briefing,
)

_CSS_INJECTED = False


def _inject_css():
    global _CSS_INJECTED
    if _CSS_INJECTED:
        return
    _CSS_INJECTED = True
    ui.add_css("""
        .brief-opener {
            background: var(--bg-card);
            border: 1px solid var(--border-strong);
            border-radius: 6px;
            padding: 1rem 1.1rem;
            margin-bottom: 1.5rem;
        }
        .brief-doc-wrap {
            background: var(--bg-card);
            border: 1px solid var(--accent);
            border-radius: 6px;
            padding: 1.4rem 1.6rem;
            margin-bottom: 1.5rem;
            width: 100%;
            box-sizing: border-box;
        }
        .brief-doc-text {
            font-size: 0.92rem;
            line-height: 1.85;
            color: var(--text-primary);
            font-family: 'IBM Plex Mono', monospace;
            white-space: pre-wrap;
        }
        .brief-placeholder {
            background: var(--bg-card);
            border: 1px dashed var(--border-strong);
            border-radius: 6px;
            padding: 3rem 1.6rem;
            text-align: center;
            margin-bottom: 1.5rem;
            width: 100%;
            box-sizing: border-box;
        }
        .brief-view-block {
            padding: 0.75rem 0;
            border-bottom: 1px solid var(--border);
        }
        .brief-view-block:last-child { border-bottom: none; }
        .brief-view-prose {
            font-size: 0.87rem;
            line-height: 1.7;
            color: var(--text-primary);
            font-family: 'IBM Plex Mono', monospace;
            margin-top: 0.35rem;
        }
        .brief-fred-row {
            display: flex;
            flex-wrap: wrap;
            gap: 0.25rem 0.8rem;
            margin-top: 0.45rem;
        }
        .brief-fred-item {
            font-size: 0.72rem;
            color: var(--text-muted);
            font-family: 'IBM Plex Mono', monospace;
        }
        .brief-asset-row {
            display: flex;
            align-items: center;
            gap: 0.65rem;
            padding: 0.28rem 0;
            border-bottom: 1px solid var(--border);
            font-family: 'IBM Plex Mono', monospace;
        }
        .brief-asset-row:last-child { border-bottom: none; }
        .brief-no-view {
            color: var(--text-faint);
            font-size: 0.8rem;
            font-style: italic;
            font-family: 'IBM Plex Mono', monospace;
            margin-top: 0.25rem;
        }
        .brief-gen-btn {
            background: transparent !important;
            border: 1px solid var(--accent) !important;
            color: var(--accent) !important;
            font-family: 'IBM Plex Mono', monospace !important;
            font-size: 0.78rem !important;
            border-radius: 4px !important;
            box-shadow: none !important;
            padding: 0 1.1rem !important;
            min-height: 2rem !important;
            flex-shrink: 0 !important;
        }
        .brief-gen-btn:hover {
            background: var(--accent-dim) !important;
        }
    """)


# ── Context builder ────────────────────────────────────────────────────────────

def _build_briefing_context(state: AppState, fred_index: dict) -> str:
    lines: list[str] = []

    if state.briefing and state.briefing.top_of_mind.strip():
        lines.append(f"TOP OF MIND: {state.briefing.top_of_mind.strip()}\n")

    lines.append("MACRO VIEWS:")
    for v in state.macro_views:
        conviction = v.conviction if v.conviction not in ("—", "") else None
        header = f"  {v.name}: {v.direction}"
        if conviction:
            header += f" ({conviction} conviction)"
        parts = [header]
        if v.lean.strip():
            parts.append(f"lean={v.lean.strip()!r}")
        signals = [s.strip() for s in v.signals if s.strip()]
        if signals:
            parts.append("signals=[" + "; ".join(signals) + "]")
        if v.counter.strip():
            parts.append(f"counter={v.counter.strip()!r}")
        fred_ids = MACRO_FRED_MAP.get(v.id, [])
        snippets = [fred_snippet(fid, fred_index) for fid in fred_ids]
        snippets = [s for s in snippets if s]
        if snippets:
            parts.append("data=[" + ", ".join(snippets) + "]")
        lines.append(" | ".join(parts))

    lines.append("\nASSET POSTURE:")
    for av in state.asset_views:
        if av.direction == "—":
            continue
        verbal = VERBAL_SCORE.get(av.direction, "no view")
        note = f" — {av.note.strip()}" if av.note and av.note.strip() else ""
        lines.append(f"  {av.name}: {verbal}{note}")

    if state.macro_notes and state.macro_notes.strip():
        lines.append(f"\nCROSS-CUTTING: {state.macro_notes.strip()}")

    if state.reconciliations:
        s = state.reconciliations[0].synthesis
        if s and s.strip():
            lines.append(f"\nLAST RECONCILIATION: {s.strip()}")

    return "\n".join(lines)


# ── Opener ─────────────────────────────────────────────────────────────────────

def _render_opener(state: AppState) -> None:
    top = state.briefing.top_of_mind.strip() if state.briefing else ""
    synthesis = ""
    if state.reconciliations:
        s = state.reconciliations[0].synthesis
        if s and s.strip():
            synthesis = s.strip()

    with ui.element("div").classes("brief-opener"):
        if not top and not synthesis:
            ui.label("No opener set — fill in Top of Mind on the Macro Views tab.").style(
                "color:var(--text-faint); font-size:0.8rem; font-style:italic; "
                "font-family:'IBM Plex Mono',monospace;"
            )
            return
        if top:
            ui.label("OPENER").style(
                "font-size:0.6rem; font-weight:700; color:var(--accent); "
                "letter-spacing:0.14em; margin-bottom:0.4rem; "
                "font-family:'IBM Plex Mono',monospace;"
            )
            ui.label(top).style(
                "font-size:0.9rem; line-height:1.6; color:var(--text-primary); "
                "font-family:'IBM Plex Mono',monospace; white-space:pre-wrap;"
            )
        if synthesis:
            ui.label("LAST SYNTHESIS").style(
                "font-size:0.6rem; font-weight:700; color:var(--text-muted); "
                "letter-spacing:0.14em; margin-top:0.75rem; margin-bottom:0.25rem; "
                "font-family:'IBM Plex Mono',monospace;"
            )
            ui.label(f'"{synthesis}"').style(
                "font-size:0.82rem; color:var(--text-muted); font-style:italic; "
                "font-family:'IBM Plex Mono',monospace;"
            )


# ── Document area helpers ──────────────────────────────────────────────────────

def _show_briefing_doc(text: str) -> None:
    ui.label("CLAUDE BRIEFING").style(
        "font-size:0.6rem; font-weight:700; color:var(--accent); "
        "letter-spacing:0.14em; margin-bottom:0.75rem; display:block; "
        "font-family:'IBM Plex Mono',monospace;"
    )
    ui.element("div").classes("brief-doc-text").text = text


def _show_briefing_placeholder(has_llm: bool) -> None:
    with ui.element("div").classes("brief-placeholder"):
        ui.label("✦").style(
            "font-size:1.4rem; color:var(--text-faint); "
            "margin-bottom:0.6rem; display:block;"
        )
        msg = (
            'Click "Generate Full Briefing" above to create a meeting-ready document from your current views.'
            if has_llm
            else "Set ANTHROPIC_API_KEY before starting the app to enable AI-generated briefings."
        )
        ui.label(msg).style(
            "font-size:0.82rem; color:var(--text-muted); "
            "font-family:'IBM Plex Mono',monospace;"
        )


def _show_briefing_error(err: str) -> None:
    ui.label(f"Generation failed — {err}").style(
        "color:#f87171; font-size:0.8rem; "
        "font-family:'IBM Plex Mono',monospace;"
    )


# ── Template flow (no-LLM fallback) ───────────────────────────────────────────

def _render_macro_template_flow(state: AppState, fred_index: dict) -> None:
    """Clean reading-mode view of all macro views — used when no LLM key is set."""
    for view in state.macro_views:
        dc = DIRECTION_COLORS.get(view.direction, DIRECTION_COLORS["No View"])
        d = days_since(view.last_touched)
        s_color = staleness_color(d)
        s_label = staleness_label(d)
        is_empty = (
            view.direction == "No View"
            and not view.lean.strip()
            and not any(s.strip() for s in view.signals)
            and not view.counter.strip()
        )
        with ui.element("div").classes("brief-view-block"):
            with ui.row().style("align-items:center; gap:0.5rem; flex-wrap:wrap;"):
                ui.element("span").style(
                    f"background:{dc['bg']}; color:{dc['text']}; padding:1px 7px; "
                    f"border-radius:4px; font-size:0.65rem; font-weight:700; "
                    f"border:1px solid {dc['text']}33; white-space:nowrap;"
                ).text = view.direction
                ui.label(view.name).style(
                    "font-weight:700; font-size:0.82rem; "
                    "font-family:'IBM Plex Mono',monospace;"
                )
                ui.html(_conviction_bars_html(view.conviction)).style("flex-shrink:0;")
                ui.label(s_label).style(
                    f"color:{s_color}; font-size:0.68rem; "
                    f"font-family:'IBM Plex Mono',monospace;"
                )
            if is_empty:
                ui.label("No view set.").classes("brief-no-view")
            else:
                ui.element("div").classes("brief-view-prose").text = macro_prose(view)
                fred_ids = MACRO_FRED_MAP.get(view.id, [])
                snippets = [s for s in (fred_snippet(f, fred_index) for f in fred_ids) if s]
                if snippets:
                    with ui.element("div").classes("brief-fred-row"):
                        for snip in snippets:
                            ui.label(snip).classes("brief-fred-item")


# ── Asset posture ──────────────────────────────────────────────────────────────

def _render_asset_posture(state: AppState) -> None:
    tenure = _load_tenure_data(state.asset_views)
    by_group = {
        "l1":           [v for v in state.asset_views if v.group == "l1"],
        "equities":     [v for v in state.asset_views if v.group == "equities"],
        "fixed_income": [v for v in state.asset_views if v.group == "fixed_income"],
    }
    group_labels = {
        "l1":           "L1 — CROSS-ASSET",
        "equities":     "EQUITIES",
        "fixed_income": "FIXED INCOME",
    }
    with ui.element("div").style(
        "background:var(--bg-card); border:1px solid var(--border); "
        "border-radius:6px; padding:0.75rem 1rem;"
    ):
        for gk in ("l1", "equities", "fixed_income"):
            views = by_group[gk]
            if not views:
                continue
            ui.label(group_labels[gk]).style(
                "font-size:0.6rem; font-weight:700; color:var(--text-muted); "
                "letter-spacing:0.15em; padding:0.4rem 0 0.25rem; "
                "font-family:'IBM Plex Mono',monospace;"
            )
            for av in views:
                t = tenure.get(av.id)
                sc = SCORE_COLORS.get(av.direction, SCORE_COLORS["—"])
                verbal = VERBAL_SCORE.get(av.direction, "no view")
                held_str = ""
                if t:
                    days = t.get("days_held")
                    unknown = t.get("unknown_start", True)
                    if days is not None:
                        held_str = f"{'>' if unknown else ''}{days}d"
                with ui.element("div").classes("brief-asset-row"):
                    ui.element("span").style(
                        f"background:{sc['bg']}; color:{sc['text']}; "
                        f"border:1px solid {sc['text']}33; border-radius:4px; "
                        f"padding:1px 6px; font-size:0.68rem; font-weight:700; "
                        f"white-space:nowrap; flex-shrink:0;"
                    ).text = av.direction
                    ui.label(av.name).style(
                        "font-size:0.82rem; min-width:130px; flex-shrink:0; "
                        "font-family:'IBM Plex Mono',monospace;"
                    )
                    ui.label(verbal).style(
                        f"font-size:0.76rem; color:{sc['text']}; min-width:120px; "
                        f"flex-shrink:0; font-family:'IBM Plex Mono',monospace;"
                    )
                    if av.note and av.note.strip():
                        ui.label(av.note.strip()).style(
                            "font-size:0.76rem; color:var(--text-muted); flex:1; "
                            "overflow:hidden; text-overflow:ellipsis; white-space:nowrap; "
                            "font-family:'IBM Plex Mono',monospace;"
                        )
                    if held_str:
                        ui.label(held_str).style(
                            "font-size:0.68rem; color:var(--text-faint); "
                            "white-space:nowrap; flex-shrink:0; "
                            "font-family:'IBM Plex Mono',monospace;"
                        )


# ── Public entry point ─────────────────────────────────────────────────────────

def render_briefing(state: AppState, save_indicator, fred_data: list | None = None) -> None:
    _inject_css()
    fred_index = {ind.id: ind for ind in (fred_data or [])}
    has_llm = llm_available()
    context = _build_briefing_context(state, fred_index)
    cached = get_cached_briefing(context) if has_llm else None

    # ── Title row ─────────────────────────────────────────────────────────────
    generate_btn = None
    with ui.row().style(
        "align-items:center; justify-content:space-between; "
        "margin-bottom:1.25rem; flex-wrap:wrap; gap:0.75rem;"
    ):
        with ui.column().style("gap:0; line-height:1.3;"):
            ui.label("MORNING BRIEFING").style(
                "font-size:0.6rem; font-weight:700; color:var(--accent); "
                "letter-spacing:0.18em; font-family:'IBM Plex Mono',monospace;"
            )
            d = date.today()
            ui.label(f"{d.strftime('%B')} {d.day}, {d.year}").style(
                "font-size:1rem; font-weight:700; color:var(--text-primary); "
                "font-family:'IBM Plex Mono',monospace;"
            )
        if has_llm:
            generate_btn = ui.button(
                "✦ Regenerate Briefing" if cached else "✦ Generate Full Briefing"
            ).classes("brief-gen-btn")

    # ── Opener ────────────────────────────────────────────────────────────────
    ui.label("OPENER").classes("section-header")
    _render_opener(state)

    # ── Macro narrative ───────────────────────────────────────────────────────
    ui.label("MACRO NARRATIVE").classes("section-header")

    if has_llm:
        # Pre-create all states; toggle visibility rather than rebuilding.
        placeholder = ui.element("div")
        with placeholder:
            _show_briefing_placeholder(has_llm=True)
        placeholder.visible = not bool(cached)

        with ui.element("div").classes("brief-doc-wrap") as doc_wrap:
            ui.label("CLAUDE BRIEFING").style(
                "font-size:0.6rem; font-weight:700; color:var(--accent); "
                "letter-spacing:0.14em; margin-bottom:0.75rem; display:block; "
                "font-family:'IBM Plex Mono',monospace;"
            )
            doc_body = ui.label(cached or "").classes("brief-doc-text")
        doc_wrap.visible = bool(cached)

        err_label = ui.label("").style(
            "color:#f87171; font-size:0.8rem; margin-bottom:1rem; "
            "font-family:'IBM Plex Mono',monospace;"
        )
        err_label.visible = False

        async def _on_generate(
            e=None, ctx=context, gb=generate_btn,
            ph=placeholder, dw=doc_wrap, db=doc_body, el=err_label,
        ):
            gb.set_text("Generating…")
            gb.disable()
            try:
                result, err = await run.io_bound(lambda: generate_briefing(ctx, True))
            except Exception as exc:
                result, err = None, str(exc)
            if result:
                db.set_text(result)
                ph.visible = False
                dw.visible = True
                el.visible = False
            else:
                detail = err or "Unknown error — check server logs."
                el.set_text(f"Generation failed: {detail}")
                el.visible = True
                ui.notify(detail, type="negative", timeout=10000)
            gb.set_text("✦ Regenerate Briefing")
            gb.enable()

        generate_btn.on("click", _on_generate)

    else:
        with ui.element("div").style(
            "background:var(--bg-card); border:1px solid var(--border); "
            "border-radius:6px; padding:0.75rem 1rem; margin-bottom:1.5rem;"
        ):
            _render_macro_template_flow(state, fred_index)

    # Cross-cutting notes
    if state.macro_notes and state.macro_notes.strip():
        with ui.element("div").style(
            "background:var(--bg-card); border:1px solid var(--border); "
            "border-radius:6px; padding:0.75rem; margin-bottom:0.75rem;"
        ):
            ui.label("CROSS-CUTTING NOTES").style(
                "font-size:0.6rem; font-weight:700; color:var(--accent); "
                "letter-spacing:0.14em; margin-bottom:0.4rem; "
                "font-family:'IBM Plex Mono',monospace;"
            )
            ui.label(state.macro_notes.strip()).style(
                "font-size:0.84rem; color:var(--text-muted); line-height:1.6; "
                "font-family:'IBM Plex Mono',monospace; white-space:pre-wrap;"
            )

    # ── Asset posture ─────────────────────────────────────────────────────────
    ui.label("ASSET POSTURE").classes("section-header").style("margin-top:1.5rem;")
    _render_asset_posture(state)
